spring:
  datasource:
    url: jdbc:h2:mem:weather
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false


openweathermap:
  key: 6a9272efb3092f1884bdeea65a4487ae


schedules:
  cron:
    dateweather: 0 0 1 * * *